window.PRODUCTS = [
  {
    "title": "Revell 7364 1:25 Ford Mustang Mach III Concept Car Model Kit",
    "condition": "New",
    "status": "active",
    "featured": false,
    "category": "Model Kit",
    "theme": "Vehicle",
    "type": "Car/Truck",
    "price": "$36.29 CAD",
    "link": "https://www.ebay.ca/itm/306677167493",
    "image": "https://i.ebayimg.com/images/g/xYIAAeSwm9NpTgNu/s-l1600.webp"
  },
  {
    "title": "Monogram 1:72 F-104C Starfighter Model Kit",
    "condition": "New",
    "status": "active",
    "featured": false,
    "category": "Model Kit",
    "theme": "Aircraft",
    "type": "Military",
    "price": "$37.43 CAD",
    "link": "https://www.ebay.ca/itm/306676917812",
    "image": "https://i.ebayimg.com/images/g/d7MAAeSwgiZpTc9Z/s-l1600.webp"
  },
  {
    "title": "Lindberg 1:25 1963 Ford Cougar II Concept Car Model Kit",
    "condition": "New",
    "status": "active",
    "featured": false,
    "category": "Model Kit",
    "theme": "Vehicle",
    "type": "Car/Truck",
    "price": "$43.49 CAD",
    "link": "https://www.ebay.ca/itm/306676867616",
    "image": "https://i.ebayimg.com/images/g/IjUAAeSw8qBpTcOJ/s-l1600.webp"
  },
  {
    "title": "Monopoly Luxe Black Gold Limited Edition Board Game",
    "condition": "New",
    "status": "active",
    "featured": false,
    "category": "Toys & Hobbies",
    "theme": "Games",
    "type": "Board & Traditional Games",
    "price": "$298.98 CAD",
    "link": "https://www.ebay.ca/itm/306627971939",
    "image": "https://i.ebayimg.com/images/g/4YoAAeSwzutpJpEb/s-l1600.webp"
  },
  {
    "title": "McFarlane NHL Series 17 Jason Blake Toronto Maple Leafs",
    "condition": "New",
    "status": "active",
    "featured": false,
    "category": "Sports/Action Figures",
    "theme": "Sports - NHL",
    "type": "Figures/Single",
    "price": "$24.98 CAD",
    "link": "https://www.ebay.ca/itm/306675154220",
    "image": "https://i.ebayimg.com/images/g/TyUAAeSwZzBpTGze/s-l1600.webp"
  },
  {
    "title": "Superman Jakks Big Figs 18\" DC Originals Tribute",
    "condition": "New",
    "status": "active",
    "featured": false,
    "category": "Sports/Action Figures",
    "theme": "Action Figures",
    "type": "Movies/Gaming",
    "price": "$240.00 CAD",
    "link": "https://www.ebay.ca/itm/306272524552",
    "image": "https://i.ebayimg.com/images/g/iMMAAOSwmexoDayv/s-l1600.webp"
  },
  {
    "title": "McFarlane NHL Series 22 Darryl Sittler Toronto Maple Leafs",
    "condition": "New",
    "status": "active",
    "featured": false,
    "category": "Sports/Action Figures",
    "theme": "Sports - NHL",
    "type": "Figures/Single",
    "price": "$34.98 CAD",
    "link": "https://www.ebay.ca/itm/306668389156",
    "image": "https://i.ebayimg.com/images/g/lsQAAeSwvthpR2wT/s-l1600.webp"
  },
  {
    "title": "McFarlane NHL Series 15 Eric Staal Carolina Hurricanes",
    "condition": "New",
    "status": "active",
    "featured": false,
    "category": "Sports/Action Figures",
    "theme": "Sports - NHL",
    "type": "Figures/Single",
    "price": "$39.50 CAD",
    "link": "https://www.ebay.ca/itm/306675100178",
    "image": "https://i.ebayimg.com/images/g/b2oAAeSwZTppTG0z/s-l1600.webp"
  },
  {
    "title": "Hobbycraft HC1585 1/48 Spitfire Mk XIV Model Kit",
    "condition": "New",
    "status": "active",
    "featured": false,
    "category": "Model Kit",
    "theme": "Aircraft",
    "type": "Military",
    "price": "$28.49 CAD",
    "link": "https://www.ebay.ca/itm/306675578413",
    "image": "https://i.ebayimg.com/images/g/nnYAAeSw67lpTLPL/s-l1600.webp"
  },
  {
    "title": "Star Trek USS Enterprise 1:1000 Model Kit (Botany Bay)",
    "condition": "New",
    "status": "active",
    "featured": false,
    "category": "Model Kit",
    "theme": "Other",
    "type": "Space",
    "price": "$47.29 CAD",
    "link": "https://www.ebay.ca/itm/306675667485",
    "image": "https://i.ebayimg.com/images/g/CysAAeSw9JlpTM~X/s-l1600.webp"
  },
  {
    "title": "McFarlane NHL Series 22 Daniel Alfredsson Ottawa Senators",
    "condition": "New",
    "status": "active",
    "featured": false,
    "category": "Sports/Action Figures",
    "theme": "Sports - NHL",
    "type": "Figures/Single",
    "price": "$27.00 CAD",
    "link": "https://www.ebay.ca/itm/306668317988",
    "image": "https://i.ebayimg.com/images/g/vTUAAeSwVdZpR1ua/s-l1600.webp"
  },
  {
    "title": "Vintage Monogram 1955 Chevy Street Machine Model Kit (1995)",
    "condition": "New",
    "status": "active",
    "featured": false,
    "category": "Model Kit",
    "theme": "Vehicle",
    "type": "Car/Truck",
    "price": "$58.49 CAD",
    "link": "https://www.ebay.ca/itm/306675621143",
    "image": "https://i.ebayimg.com/images/g/PhoAAeSwOJxpTMWO/s-l1600.webp"
  },
  {
    "title": "Star Trek Lt. Uhura 50th Anniversary Barbie Doll Mattel Collector Edition New",
    "condition": "New",
    "status": "active",
    "featured": false,
    "category": "Dolls, Clothing & Accessories",
    "theme": "Dolls & Doll Playsets",
    "type": "Collectibles",
    "price": "$270.00 CAD",
    "link": "https://www.ebay.ca/itm/306387845185",
    "image": "https://i.ebayimg.com/images/g/I9QAAeSwGCtpRdyr/s-l1600.webp"
  },
  {
    "title": "McFarlane NHL Series 22 Mats Sundin Vancouver Canucks",
    "condition": "New",
    "status": "active",
    "featured": false,
    "category": "Sports/Action Figures",
    "theme": "Sports - NHL",
    "type": "Figures/Single",
    "price": "$36.50 CAD",
    "link": "https://www.ebay.ca/itm/306668354076",
    "image": "https://i.ebayimg.com/images/g/H4AAAeSwcdBpR2Ls/s-l1600.webp"
  },
  {
    "title": "Little People Collector Britney Spears Special Edition",
    "condition": "New",
    "status": "active",
    "featured": false,
    "category": "Toys & Hobbies",
    "theme": "Preschool Toys & Pretend Play",
    "type": "Little People",
    "price": "$68.98 CAD",
    "link": "https://www.ebay.ca/itm/306650564518",
    "image": "https://i.ebayimg.com/images/g/MYAAAeSw9hlpQIPe/s-l1600.webp"
  },
  {
    "title": "Wayne Gretzky Ford Canada Framed Photo with Pins",
    "condition": "New",
    "status": "active",
    "featured": false,
    "category": "Sports Memorabilia, Fan Shop & Sports Cards",
    "theme": "Hockey-NHL",
    "type": "Collectibles",
    "price": "$210.00 CAD",
    "link": "https://www.ebay.ca/itm/306628007712",
    "image": "https://i.ebayimg.com/images/g/v-gAAeSwlaJpJppd/s-l1600.webp"
  },
  {
    "title": "Transformers Robots in Disguise Collection 6-Pack",
    "condition": "New",
    "status": "active",
    "featured": false,
    "category": "Sports/Action Figures",
    "theme": "Action Figures",
    "type": "Movies/Gaming",
    "price": "$85.00 CAD",
    "link": "https://www.ebay.ca/itm/306620466301",
    "image": "https://i.ebayimg.com/images/g/LgEAAeSwogdpRdwz/s-l1600.webp"
  },
  {
    "title": "McFarlane NHL Series 20 Dion Phaneuf Calgary Flames",
    "condition": "New",
    "status": "active",
    "featured": false,
    "category": "Sports/Action Figures",
    "theme": "Sports - NHL",
    "type": "Figures/Single",
    "price": "$24.50 CAD",
    "link": "https://www.ebay.ca/itm/306668373681",
    "image": "https://i.ebayimg.com/images/g/sqcAAeSwfMdpR2eG/s-l1600.webp"
  },
  {
    "title": "McFarlane NHL Series 22 Martin Brodeur New Jersey Devils",
    "condition": "New",
    "status": "active",
    "featured": false,
    "category": "Sports/Action Figures",
    "theme": "Sports - NHL",
    "type": "Figures/Single",
    "price": "$42.98 CAD",
    "link": "https://www.ebay.ca/itm/306670399494",
    "image": "https://i.ebayimg.com/images/g/~24AAeSwPMtpSN9d/s-l1600.webp"
  },
  {
    "title": "Star Trek Spock Barbie 50th Anniversary Collector Doll",
    "condition": "New",
    "status": "active",
    "featured": false,
    "category": "Dolls, Clothing & Accessories",
    "theme": "Dolls & Doll Playsets",
    "type": "Collectibles",
    "price": "$150.00 CAD",
    "link": "https://www.ebay.ca/itm/306274472136",
    "image": "https://i.ebayimg.com/images/g/TbUAAeSwWXpoDy7C/s-l1600.webp"
  },
  {
    "title": "LEGO Ideas International Space Station 21321 (Retired)",
    "condition": "New",
    "status": "active",
    "featured": false,
    "category": "Construction Set",
    "theme": "LEGO",
    "type": "Space",
    "price": "$249.98 CAD",
    "link": "https://www.ebay.ca/itm/306659718545",
    "image": "https://i.ebayimg.com/images/g/VZ0AAeSwKpxpRd0u/s-l1600.webp"
  },
  {
    "title": "WWE StackDown RAW Ring Building Set Rock & Cena",
    "condition": "New",
    "status": "active",
    "featured": false,
    "category": "Construction Set",
    "theme": "Other",
    "type": "Other",
    "price": "$223.98 CAD",
    "link": "https://www.ebay.ca/itm/306272474172",
    "image": "https://i.ebayimg.com/images/g/qUgAAeSw2FtpRdqF/s-l1600.webp"
  },
  {
    "title": "Red Baron 1917 Fokker DR1 Triplane Metal Desk Model",
    "condition": "New",
    "status": "active",
    "featured": false,
    "category": "Collectibles & Art",
    "theme": "Aviation",
    "type": "Desk & Shelf Models",
    "price": "$80.00 CAD",
    "link": "https://www.ebay.ca/itm/306668519774",
    "image": "https://i.ebayimg.com/images/g/MxYAAeSwih9pR4-a/s-l1600.webp"
  },
  {
    "title": "LEGO Creator Apollo 11 Lunar Lander 10266 (Retired)",
    "condition": "New",
    "status": "active",
    "featured": false,
    "category": "Construction Set",
    "theme": "LEGO",
    "type": "Space",
    "price": "$260.00 CAD",
    "link": "https://www.ebay.ca/itm/306659729015",
    "image": "https://i.ebayimg.com/images/g/CpAAAeSwdZtpQIMX/s-l1600.webp"
  },
  {
    "title": "LEGO Ideas NASA Apollo Saturn V 21309 (Retired)",
    "condition": "New",
    "status": "active",
    "featured": false,
    "category": "Construction Set",
    "theme": "LEGO",
    "type": "Space",
    "price": "$550.00 CAD",
    "link": "https://www.ebay.ca/itm/306274018718",
    "image": "https://i.ebayimg.com/images/g/VbQAAOSwzcNoDtNg/s-l960.webp"
  },
  {
    "title": "NEW LEGO 75137 STAR WARS RETIRED Chamber Boba Fett Han Solo Carbonite SEALED",
    "condition": "New",
    "status": "active",
    "featured": false,
    "category": "Construction Set",
    "theme": "LEGO",
    "type": "Space",
    "price": "$126.49 CAD",
    "link": "https://www.ebay.ca/itm/306678470770",
    "image": "https://i.ebayimg.com/images/g/ieoAAeSw9BBpTuyG/s-l1600.webp"
  },
  {
    "title": "3D Deco Light FX Hockey Puck LED Night Light New Condition Battery Powered",
    "condition": "New",
    "status": "active",
    "featured": false,
    "category": "Home",
    "theme": "Lighting",
    "type": "Night Lights",
    "price": "$18.00 CAD",
    "link": "https://www.ebay.ca/itm/306678515916",
    "image": "https://i.ebayimg.com/images/g/B7kAAeSw67lpTvWK/s-l1600.webp"
  },
  {
    "title": "McFarlane Toys NHL Series 20 Jerome Iginla #13 Calgary Flame NEW",
    "condition": "New",
    "status": "active",
    "featured": false,
    "category": "Sports/Action Figures",
    "theme": "Sports - NHL",
    "type": "Figures/Single",
    "price": "$32.98 CAD",
    "link": "https://www.ebay.ca/itm/306678564092",
    "image": "https://i.ebayimg.com/images/g/C~IAAeSwzLRpTwOP/s-l1600.webp"
  },
  {
    "title": "Royal Canadian Air Farce – The Complete Farce VHS Box Set Volume 1-3",
    "condition": "New",
    "status": "active",
    "featured": false,
    "category": "Books, Movies & Music",
    "theme": "Movies & TV",
    "type": "VHS Tapes",
    "price": "$32.98 CAD",
    "link": "https://www.ebay.ca/itm/306678591050",
    "image": "https://i.ebayimg.com/images/g/bMwAAeSw0OVpTwof/s-l1600.webp"
  },
  {
    "title": "NHL Imports Dragon 2.5″ Series 1 Collectible NHL Mini Figures New Sealed",
    "condition": "New",
    "status": "active",
    "featured": false,
    "category": "Sports/Action Figures",
    "theme": "Sports - NHL",
    "type": "Figures/Set",
    "price": "$32.98 CAD",
    "link": "https://www.ebay.ca/itm/306678807543",
    "image": "https://i.ebayimg.com/images/g/3iAAAeSwdBxpTyy4/s-l1600.webp"
  },
  {
    "title": "Erik Karlsson Ottawa Senators Funko Pop! Hockey Vinyl Exclusive NHL Collectible",
    "condition": "New",
    "status": "sold",
    "featured": false,
    "category": "Sports/Action Figures",
    "theme": "Sports - NHL",
    "type": "Figures/Single",
    "price": "$49.98 CAD",
    "link": "https://www.ebay.ca/itm/306678856258",
    "image": "https://i.ebayimg.com/images/g/OTMAAeSwMX9pTzVn/s-l1600.webp"
  },
  {
    "title": "McFarlane Toys – Fallout Lucy, Maximus & The Ghoul 3‑Pack (Gold Label) Mint New",
    "condition": "New",
    "status": "active",
    "featured": false,
    "category": "Sports/Action Figures",
    "theme": "Action Figures",
    "type": "Movies/Gaming",
    "price": "$140.58 CAD",
    "link": "https://www.ebay.ca/itm/306678905899",
    "image": "https://i.ebayimg.com/images/g/OxIAAeSwRtJpTz4e/s-l1600.webp"
  },
  {
    "title": "Mortal Kombat Klassic Kitana McFarlane Red Platinum Edition 7\" Figure New",
    "condition": "New",
    "status": "active",
    "featured": false,
    "category": "Sports/Action Figures",
    "theme": "Action Figures",
    "type": "Movies/Gaming",
    "price": "$68.98 CAD",
    "link": "https://www.ebay.ca/itm/306678929552",
    "image": "https://i.ebayimg.com/images/g/tyAAAeSw3QdpUEj1/s-l1600.webp"
  },
  {
    "title": "DOOM: The Dark Ages Doom Slayer 7in Deluxe McFarlane Elite Edition Mint NIB",
    "condition": "New",
    "status": "active",
    "featured": false,
    "category": "Sports/Action Figures",
    "theme": "Action Figures",
    "type": "Movies/Gaming",
    "price": "$239.98 CAD",
    "link": "https://www.ebay.ca/itm/306678950467",
    "image": "https://i.ebayimg.com/images/g/b-wAAeSwQZBpUEAJ/s-l1600.webp"
  },
  {
    "title": "Pokémon Select Ceruledge Action Figure by Jazwares, New, MIB",
    "condition": "New",
    "status": "sold",
    "featured": false,
    "category": "Sports/Action Figures",
    "theme": "Action Figures",
    "type": "Movies/Gaming",
    "price": "$84.49 CAD",
    "link": "https://www.ebay.ca/itm/306682459012",
    "image": "https://i.ebayimg.com/images/g/DtMAAeSwz2NpUFpA/s-l500.jpg"
  },
  {
    "title": "Athearn HO GO Transit Bombardier Coach 3-Car Set \"ATH2581\" #200/#2307/#2330",
    "condition": "New",
    "status": "active",
    "featured": false,
    "category": "Toys & Hobbies",
    "theme": "Model Railroads & Trains",
    "type": "Railroads & Trains",
    "price": "$398.98 CAD",
    "link": "https://www.ebay.ca/itm/306681709646",
    "image": "https://i.ebayimg.com/images/g/LnwAAeSwk89pUaI4/s-l1600.webp"
  },
  {
    "title": "Patrick Roy Colorado Avalanche McFarlane NHL Figure White Jersey Sealed Series 6",
    "condition": "New",
    "status": "active",
    "featured": false,
    "category": "Sports/Action Figures",
    "theme": "Sports - NHL",
    "type": "Figures/Single",
    "price": "$59.98 CAD",
    "link": "https://www.ebay.ca/itm/306681771299",
    "image": "https://i.ebayimg.com/images/g/OR0AAeSwJo9pUayM/s-l1600.webp"
  },
  {
    "title": "McFarlane Toys NHL SportsPicks Series 14 – Marcus Näslund #19",
    "condition": "New",
    "status": "active",
    "featured": false,
    "category": "Sports/Action Figures",
    "theme": "Sports - NHL",
    "type": "Figures/Single",
    "price": "$26.98 CAD",
    "link": "https://www.ebay.ca/itm/306681827295",
    "image": "https://i.ebayimg.com/images/g/hwcAAeSwGWlpUbqJ/s-l1600.webp"
  },
  {
    "title": "Yvan Cournoyer McFarlane NHL Montreal Canadiens Action Figure Series 1",
    "condition": "New",
    "status": "sold",
    "featured": false,
    "category": "Sports/Action Figures",
    "theme": "Sports - NHL",
    "type": "Figures/Single",
    "price": "$26.98 CAD",
    "link": "https://www.ebay.ca/itm/306681863436",
    "image": "https://i.ebayimg.com/images/g/rB4AAeSwNntpUcL9/s-l1600.webp"
  },
  {
    "title": "Jeremy Roenick McFarlane NHL LA Kings Action Figure Series 12 Mint",
    "condition": "New",
    "status": "active",
    "featured": false,
    "category": "Sports/Action Figures",
    "theme": "Sports - NHL",
    "type": "Figures/Single",
    "price": "$18.98 CAD",
    "link": "https://www.ebay.ca/itm/306681966593",
    "image": "https://i.ebayimg.com/images/g/GoYAAeSwsTBpUdNK/s-l1600.webp"
  },
  {
    "title": "Daniel Sedin McFarlane NHL Vancouver Canucks Action Figure Series 12 Mint",
    "condition": "New",
    "status": "active",
    "featured": false,
    "category": "Sports/Action Figures",
    "theme": "Sports - NHL",
    "type": "Figures/Single",
    "price": "$22.98 CAD",
    "link": "https://www.ebay.ca/itm/306682029084",
    "image": "https://i.ebayimg.com/images/g/CQYAAeSwQxtpUd30/s-l1600.webp"
  },
  {
    "title": "McFarlane NHL Wayne Gretzky LA Kings Vintage Action Figure Series 1 New",
    "condition": "New",
    "status": "active",
    "featured": false,
    "category": "Sports/Action Figures",
    "theme": "Sports - NHL",
    "type": "Figures/Single",
    "price": "$30.98 CAD",
    "link": "https://www.ebay.ca/itm/306682070918",
    "image": "https://i.ebayimg.com/images/g/LSwAAeSw~W5pUeTj/s-l1600.webp"
  },
  {
    "title": "McFarlane Toys NHL Joe Sakic Colorado Avalanche White Jersey Series 9 Figure MIB",
    "condition": "New",
    "status": "active",
    "featured": false,
    "category": "Sports/Action Figures",
    "theme": "Sports - NHL",
    "type": "Figures/Single",
    "price": "$27.98 CAD",
    "link": "https://www.ebay.ca/itm/306682090324",
    "image": "https://i.ebayimg.com/images/g/nQMAAeSwg5ppUenr/s-l1600.webp"
  },
  {
    "title": "Imports Dragon NHL Mark Giordano Calgary Flames Action Figure MIB",
    "condition": "New",
    "status": "active",
    "featured": false,
    "category": "Sports/Action Figures",
    "theme": "Sports - NHL",
    "type": "Figures/Single",
    "price": "$27.98 CAD",
    "link": "https://www.ebay.ca/itm/306682119392",
    "image": "https://i.ebayimg.com/images/g/po0AAeSwXXxpUe~V/s-l1600.webp"
  },
  {
    "title": "Joe Thornton McFarlane NHL San Jose Sharks Early Trade Collectible Figure MIB",
    "condition": "New",
    "status": "active",
    "featured": false,
    "category": "Sports/Action Figures",
    "theme": "Sports - NHL",
    "type": "Figures/Single",
    "price": "$49.98 CAD",
    "link": "https://www.ebay.ca/itm/306682145899",
    "image": "https://i.ebayimg.com/images/g/56IAAeSweM1pUfhg/s-l1600.webp"
  },
  {
    "title": "1:87 Scale Golden Wheel MAN Semi Trailer Pennzoil Racing HO Scale New",
    "condition": "New",
    "status": "active",
    "featured": false,
    "category": "Toys & Hobbies",
    "theme": "Diecast & Toy Vehicles",
    "type": "Cars, Trucks & Vans",
    "price": "$19.99 CAD",
    "link": "https://www.ebay.ca/itm/306682167693",
    "image": "https://i.ebayimg.com/images/g/BwgAAeSwe~lpUgHy/s-l1600.webp"
  },
  {
    "title": "1:87 Scale Golden Wheel MAN Semi Trailer Pennzoil Racing HO Scale New",
    "condition": "New",
    "status": "active",
    "featured": false,
    "category": "Toys & Hobbies",
    "theme": "Diecast & Toy Vehicles",
    "type": "Cars, Trucks & Vans",
    "price": "$19.99 CAD",
    "link": "https://www.ebay.ca/itm/306682167693",
    "image": "https://i.ebayimg.com/images/g/BwgAAeSwe~lpUgHy/s-l1600.webp"
  },
  {
    "title": "1:87 Scale Golden Wheel MAN Semi Trailer Pennzoil Racing HO Scale New",
    "condition": "New",
    "status": "active",
    "featured": false,
    "category": "Toys & Hobbies",
    "theme": "Diecast & Toy Vehicles",
    "type": "Cars, Trucks & Vans",
    "price": "$19.99 CAD",
    "link": "https://www.ebay.ca/itm/306682167693",
    "image": "https://i.ebayimg.com/images/g/BwgAAeSwe~lpUgHy/s-l1600.webp"
  },
  {
    "title": "1:87 Scale Golden Wheel MAN Semi Trailer 7Up HO Scale New",
    "condition": "New",
    "status": "active",
    "featured": false,
    "category": "Toys & Hobbies",
    "theme": "Diecast & Toy Vehicles",
    "type": "Cars, Trucks & Vans",
    "price": "$19.99 CAD",
    "link": "https://www.ebay.ca/itm/306682181225",
    "image": "https://i.ebayimg.com/images/g/MwQAAeSwDUFpUgVt/s-l1600.webp"
  },
  {
    "title": "McFarlane Fallout Vault Boy Posed Figure Gold Label 3750 Limited Movie Maniacs",
    "condition": "New",
    "status": "sold",
    "featured": false,
    "category": "Sports/Action Figures",
    "theme": "Action Figures",
    "type": "Movies/Gaming",
    "price": "$78.98 CAD",
    "link": "https://www.ebay.ca/itm/306682263330",
    "image": "https://i.ebayimg.com/images/g/kcgAAeSw7-ZpUhyj/s-l1600.webp"
  },
  {
    "title": "Funko Pop Disney Mad Hatter #36 Retired Vaulted 2012 Vinyl Figure",
    "condition": "New",
    "status": "active",
    "featured": false,
    "category": "Collectible Figures & Bobbleheads",
    "theme": "Bobbleheads",
    "type": "Funko",
    "price": "$184.98 CAD",
    "link": "https://www.ebay.ca/itm/306692302938",
    "image": "https://i.ebayimg.com/images/g/fnMAAeSwY5dpWYg6/s-l1600.webp"
  },
  {
    "title": "Funko Pop Disney Princess Belle #1021 Beauty and the Beast Vinyl Figure",
    "condition": "New",
    "status": "active",
    "featured": false,
    "category": "Collectible Figures & Bobbleheads",
    "theme": "Bobbleheads",
    "type": "Funko",
    "price": "$19.98 CAD",
    "link": "https://www.ebay.ca/itm/306692325242",
    "image": "https://i.ebayimg.com/images/g/lEgAAeSwyElpWY1q/s-l1600.webp"
  },
  {
    "title": "Funko Pop Movies Turbo Man #1167 Jingle All The Way Figure",
    "condition": "New",
    "status": "active",
    "featured": false,
    "category": "Collectible Figures & Bobbleheads",
    "theme": "Bobbleheads",
    "type": "Funko",
    "price": "$16.98 CAD",
    "link": "https://www.ebay.ca/itm/306692362188",
    "image": "https://i.ebayimg.com/images/g/8B0AAeSwVCtpWZfd/s-l1600.webp"
  },
  {
    "title": "McFarlane Fallout Movie Maniacs Season 1 4 Pack Figures Sealed",
    "condition": "New",
    "status": "active",
    "featured": false,
    "category": "Sports/Action Figures",
    "theme": "Action Figures",
    "type": "Movies/Gaming",
    "price": "$99.98 CAD",
    "link": "https://www.ebay.ca/itm/306694343159",
    "image": "https://i.ebayimg.com/images/g/cAwAAeSwd4BpWyPe/s-l1600.webp"
  },
  {
    "title": "Kermit Bob Cratchit Tiny Tim Funko Pop! Movies 1457 The Muppet Christmas Carol",
    "condition": "New",
    "status": "active",
    "featured": false,
    "category": "Collectible Figures & Bobbleheads",
    "theme": "Bobbleheads",
    "type": "Funko",
    "price": "$28.98 CAD",
    "link": "https://www.ebay.ca/itm/306699317913",
    "image": "https://i.ebayimg.com/images/g/R-UAAeSwPLdpXtjP/s-l1600.webp"
  },
  {
    "title": "McFarlane Toys NHL Series 4 Darryl Sitler #94 Edmonton Oilers",
    "condition": "New",
    "status": "active",
    "featured": false,
    "category": "Sports/Action Figures",
    "theme": "Sports - NHL",
    "type": "Figures/Single",
    "price": "$15.98 CAD",
    "link": "https://www.ebay.ca/itm/306699732704",
    "image": "https://i.ebayimg.com/images/g/eUoAAeSwRadpXzDs/s-l1600.webp"
  },
  {
    "title": "McFarlane Toys MLB Series 4 Ichiro Suzuki #51 Seattle Mariners",
    "condition": "New",
    "status": "active",
    "featured": false,
    "category": "Sports/Action Figures",
    "theme": "Sports - MLB",
    "type": "Figures/Single",
    "price": "$26.98 CAD",
    "link": "https://www.ebay.ca/itm/306699746013",
    "image": "https://i.ebayimg.com/images/g/dLoAAeSwhWNpXzjU/s-l1600.webp"
  },
  {
    "title": "Hobbycraft HC1391 CF-100 Canuck 1:72 Scale Plastic Model Kit Vintage Sealed Part",
    "condition": "New",
    "status": "sold",
    "featured": false,
    "category": "Model Kit",
    "theme": "Aircraft",
    "type": "Military",
    "price": "$45.98 CAD",
    "link": "https://www.ebay.ca/itm/306699784278",
    "image": "https://i.ebayimg.com/images/g/NQsAAeSwBPhpX0GR/s-l1600.webp"
  },
  {
    "title": "Funko Pop! Television I Love Lucy #654 Lucille Ball Vinyl Figure Special Edition",
    "condition": "New",
    "status": "active",
    "featured": false,
    "category": "Collectible Figures & Bobbleheads",
    "theme": "Bobbleheads",
    "type": "Funko",
    "price": "$35.98 CAD",
    "link": "https://www.ebay.ca/itm/306701243942",
    "image": "https://i.ebayimg.com/images/g/ntYAAeSwOx5pYGil/s-l1600.webp"
  },
  {
    "title": "Funko Pop Disney Pixar Luca Paguro Land #1053 Vinyl Figure Excellent Condition",
    "condition": "New",
    "status": "active",
    "featured": false,
    "category": "Collectible Figures & Bobbleheads",
    "theme": "Bobbleheads",
    "type": "Funko",
    "price": "$9.98 CAD",
    "link": "https://www.ebay.ca/itm/306701254516",
    "image": "https://i.ebayimg.com/images/g/HtoAAeSwuutpYHBl/s-l1600.webp"
  },
  {
    "title": "PC The PC Insider’s 2-6-0 Comeback Express Edition HO Scale Train Set Sealed",
    "condition": "New",
    "status": "active",
    "featured": false,
    "category": "Toys & Hobbies",
    "theme": "Model Railroads & Trains",
    "type": "Railroads & Trains",
    "price": "$264.98 CAD",
    "link": "https://www.ebay.ca/itm/306702950919",
    "image": "https://i.ebayimg.com/images/g/WKAAAeSwzEppYcsz/s-l1600.webp"
  },
  {
    "title": "Funko Pop! 225 Funtime Freddy Chase Five Nights at Freddy’s Sister Location MIB",
    "condition": "New",
    "status": "active",
    "featured": false,
    "category": "Collectible Figures & Bobbleheads",
    "theme": "Bobbleheads",
    "type": "Funko",
    "price": "$109.98 CAD",
    "link": "https://www.ebay.ca/itm/306703071901",
    "image": "https://i.ebayimg.com/images/g/srsAAeSwn8VpYev3/s-l1600.webp"
  },
  {
    "title": "Funko Pop South Park Mint‑Berry Crunch #06 2017 Summer Con Exclusive Vaulted",
    "condition": "New",
    "status": "active",
    "featured": false,
    "category": "Collectible Figures & Bobbleheads",
    "theme": "Bobbleheads",
    "type": "Funko",
    "price": "$22.98 CAD",
    "link": "https://www.ebay.ca/itm/306703126554",
    "image": "https://i.ebayimg.com/images/g/OMUAAeSwDDZpYfXG/s-l1600.webp"
  },
  {
    "title": "Funko Pop Rick and Morty Toxic Rick #335 Glow in the Dark Vaulted",
    "condition": "New",
    "status": "active",
    "featured": false,
    "category": "Collectible Figures & Bobbleheads",
    "theme": "Bobbleheads",
    "type": "Funko",
    "price": "$25.98 CAD",
    "link": "https://www.ebay.ca/itm/306703149721",
    "image": "https://i.ebayimg.com/images/g/E-UAAeSwjE1pYf0-/s-l1600.webp"
  },
  {
    "title": "Funko Pop Rick and Morty Toxic Morty #336 Glow in the Dark Vaulted",
    "condition": "New",
    "status": "active",
    "featured": false,
    "category": "Collectible Figures & Bobbleheads",
    "theme": "Bobbleheads",
    "type": "Funko",
    "price": "$25.98 CAD",
    "link": "https://www.ebay.ca/itm/306703153523",
    "image": "https://i.ebayimg.com/images/g/siwAAeSwqgJpYf6I/s-l1600.webp"
  },
  {
    "title": "Funko Pop The Walking Dead Glenn Rhee #35 Television Vinyl Figure",
    "condition": "New",
    "status": "active",
    "featured": false,
    "category": "Collectible Figures & Bobbleheads",
    "theme": "Bobbleheads",
    "type": "Funko",
    "price": "$57.98 CAD",
    "link": "https://www.ebay.ca/itm/306703193079",
    "image": "https://i.ebayimg.com/images/g/87gAAeSwxEVpYgak/s-l1600.webp"
  },
  {
    "title": "Funko Pop The Godfather Michael Corleone #1201 Movie Vinyl Collectible",
    "condition": "New",
    "status": "active",
    "featured": false,
    "category": "Collectible Figures & Bobbleheads",
    "theme": "Bobbleheads",
    "type": "Funko",
    "price": "$18.78 CAD",
    "link": "https://www.ebay.ca/itm/306703224184",
    "image": "https://i.ebayimg.com/images/g/LxwAAeSwyQppYg1k/s-l1600.webp"
  },
  {
    "title": "Funko Pop! Star Wars Obi-Wan Kenobi #273 Walgreens Exclusive Vinyl Figure",
    "condition": "New",
    "status": "active",
    "featured": false,
    "category": "Collectible Figures & Bobbleheads",
    "theme": "Bobbleheads",
    "type": "Funko",
    "price": "$34.28 CAD",
    "link": "https://www.ebay.ca/itm/306703248584",
    "image": "https://i.ebayimg.com/images/g/O1cAAeSwvBxpYhUE/s-l1600.webp"
  },
  {
    "title": "Hobbycraft HC1392 Avro CF-105 Arrow 1:72 Scale Aircraft Model Kit Sealed Parts",
    "condition": "New",
    "status": "active",
    "featured": false,
    "category": "Model Kit",
    "theme": "Aircraft",
    "type": "Military",
    "price": "$182.27 CAD",
    "link": "https://www.ebay.ca/itm/306704246669",
    "image": "https://i.ebayimg.com/images/g/iW8AAeSwJr1pYsTL/s-l1600.webp"
  },
  {
    "title": "Hobbycraft Hasegawa 1147 Lockheed P-3C Orion 1:144 Scale Model Kit Sealed Parts",
    "condition": "New",
    "status": "active",
    "featured": false,
    "category": "Model Kit",
    "theme": "Aircraft",
    "type": "Military",
    "price": "$54.98 CAD",
    "link": "https://www.ebay.ca/itm/306704297558",
    "image": "https://i.ebayimg.com/images/g/gfQAAeSwE3ppYs8h/s-l1600.webp"
  },
  {
    "title": "Funko Pop! Transformers Grimlock #69 Vinyl Figure Limited Edition",
    "condition": "New",
    "status": "active",
    "featured": false,
    "category": "Collectible Figures & Bobbleheads",
    "theme": "Bobbleheads",
    "type": "Funko",
    "price": "$32.58 CAD",
    "link": "https://www.ebay.ca/itm/306704370365",
    "image": "https://i.ebayimg.com/images/g/EOYAAeSwCsxpYuE-/s-l1600.webp"
  },
  {
    "title": "Funko Pop! DC Peacemaker Eagly (Flocked) #1236 Amazon Exclusive Vinyl Figure",
    "condition": "New",
    "status": "active",
    "featured": false,
    "category": "Collectible Figures & Bobbleheads",
    "theme": "Bobbleheads",
    "type": "Funko",
    "price": "$34.68 CAD",
    "link": "https://www.ebay.ca/itm/306704444382",
    "image": "https://i.ebayimg.com/images/g/fysAAeSw5ItpYubH/s-l1600.webp"
  },
  {
    "title": "Funko Pop! Movies A Goofy Movie Powerline #1340 2023 Wondrous Convention LE",
    "condition": "New",
    "status": "active",
    "featured": false,
    "category": "Collectible Figures & Bobbleheads",
    "theme": "Bobbleheads",
    "type": "Funko",
    "price": "$52.98 CAD",
    "link": "https://www.ebay.ca/itm/306704501901",
    "image": "https://i.ebayimg.com/images/g/Wh4AAeSwwbRpYv1Y/s-l1600.webp"
  },
  {
    "title": "Funko Pop! Movies Predator #620 Vinyl Figure Sci-Fi Collectible",
    "condition": "New",
    "status": "active",
    "featured": false,
    "category": "Collectible Figures & Bobbleheads",
    "theme": "Bobbleheads",
    "type": "Funko",
    "price": "$21.88 CAD",
    "link": "https://www.ebay.ca/itm/306704656748",
    "image": "https://i.ebayimg.com/images/g/DkYAAeSwSytpYzhX/s-l1600.webp"
  },
  {
    "title": "Funko Pop! Disney Pixar Toy Story Buzz #169 Vinyl Figure Excellent Condition",
    "condition": "New",
    "status": "active",
    "featured": false,
    "category": "Collectible Figures & Bobbleheads",
    "theme": "Bobbleheads",
    "type": "Funko",
    "price": "$18.59 CAD",
    "link": "https://www.ebay.ca/itm/306704720554",
    "image": "https://i.ebayimg.com/images/g/wwgAAeSwZ1dpY0sY/s-l1600.webp"
  },
  {
    "title": "Funko Pop! Disney Pixar Toy Story Woody #168 Vinyl Figure Excellent Condition",
    "condition": "New",
    "status": "active",
    "featured": false,
    "category": "Collectible Figures & Bobbleheads",
    "theme": "Bobbleheads",
    "type": "Funko",
    "price": "$20.48 CAD",
    "link": "https://www.ebay.ca/itm/306704734198",
    "image": "https://i.ebayimg.com/images/g/yO0AAeSw90VpY02h/s-l1600.webp"
  },
  {
    "title": "Funko Pop! Disney Villains Dr. Facilier #1207 Hot Topic Exclusive Vinyl Figure",
    "condition": "New",
    "status": "active",
    "featured": false,
    "category": "Collectible Figures & Bobbleheads",
    "theme": "Bobbleheads",
    "type": "Funko",
    "price": "$21.98 CAD",
    "link": "https://www.ebay.ca/itm/306705430075",
    "image": "https://i.ebayimg.com/images/g/FiQAAeSwONBpY-Bl/s-l1600.webp"
  },
  {
    "title": "Funko Pop! Disney Scar with Hyenas #1204 Hot Topic Exclusive Lion King Vinyl",
    "condition": "New",
    "status": "active",
    "featured": false,
    "category": "Collectible Figures & Bobbleheads",
    "theme": "Bobbleheads",
    "type": "Funko",
    "price": "$53.46 CAD",
    "link": "https://www.ebay.ca/itm/306705610530",
    "image": "https://i.ebayimg.com/images/g/jqUAAeSwv8dpZAS2/s-l1600.webp"
  }
];
